version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - selenium
    networks:
      - app-network
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
